### ISSUE TITLE
404 -> https://etfdb.com/api/screener/

### ISSUE THREAD

**Issue by xxx44yyy** [janlukasschroeder/etfdb-api#1]
404 -> https://etfdb.com/api/screener/

**Comment by janlukasschroeder** [comment]
That's because you performed a GET request. You have to perform a POST request. In other words: you can't type that URL into your browser. Use Postman or curl to perform a POST request.

Type in your terminal
```bash
curl -d '{"only":["meta","data",null]}' -H "Content-Type: application/json" -X POST https://etfdb.com/api/screener/
```
